<html>
	<head>
		<title>Welcome to Nissan - Behind the Hit</title>	
	</head>
	<body bgcolor="#ffffff" link="#72a5b4" vlink="#72a5b4"> 
    	<center>
            <table style="margin: 0pt; padding: 0pt; border-collapse: collapse; text-align: left;" align="center" bgcolor="#f6f5f3" border="0" cellpadding="0" cellspacing="0" width="580">
                <tr>
                	<td style="padding:5px 30px 32px;"><font color="#413000" face="Arial, Helvetica, sans-serif" size="2" style="font-size: 12px; line-height: 16px;">Dear <?php echo $this->name ?>,</font><br><br><font color="#8a7967" face="Arial, Helvetica, sans-serif" size="2" style="font-size: 12px; line-height: 16px;">We all forget a password here and there. Your temporary password for
                    Nissan - Behind the Hit is: <?php echo $this->newPassword; ?><br><br>Once you log in with this password, you can create a new password within your
                        Profile<br><br>Thanks!</font></td>
                </tr>
                <tr>
                	<td height="162">&nbsp;</td>
                </tr>
            </table>
        </center>
    </body>
</html>
