                    <div id="page_header">
                        <h2>Forgot Password</h2>
                        <p class="page_info"></p>
                    </div>
                    <form action="<?php echo $this->forgotPassForm->getAction(); ?>" id="register" method="post">
                        <div class="form_wrapper">
                            <div class="form_bg">
                        <?php if($this->forgotPassForm->getMessages()): ?>
                            <div class="errors">
                            <ul class="form-errors">
                                <?php foreach($this->forgotPassForm->getErrorMessagesList() as $message): ?>
                                    <li><?php echo $message ?></li>
                                <?php endforeach; ?>
                            </ul>
                            </div>
                        <?php endif; ?>
                        <ul>
                            <li class="textinput">
                                <label>Email*</label>
                                <div class="textinput">
                                    <?php echo $this->forgotPassForm->emailAddress; ?>
                                </div>
                            </li>
                        </ul>
                           <div class="clear"></div>
                            <fieldset>
                                <button type="submit" id="reg_submit"></button>
                            </fieldset>
                            <div class="clear"></div>
                        </div><!-- closes form bg -->
                    </div>     
                </form>