                    <div id="page_header">
                        <h2>Change Password</h2>
                        <p class="page_info"></p>
                    </div>
                    <form action="<?php echo $this->form->getAction(); ?>" id="register" method="post">
                    <div class="form_wrapper">
                        <div class="form_bg">
                        <?php if($this->form->getMessages()): ?>
                            <div class="errors">
                            <ul class="form-errors">
                                <?php foreach($this->form->getMessages() as $message): ?>
                                    <li><?php echo $message ?></li>
                                <?php endforeach; ?>
                            </ul>
                            </div>
                        <?php endif; ?>
                        <ul>
                            <li class="textinput">
                                <label>Password*</label>
                                <div class="textinput">
                                    <?php echo $this->form->password; ?>
                                </div>
                            </li>
                            <li class="textinput">
                                <label>Confirm Password*</label>
                                <div class="textinput">
                                    <?php echo $this->form->confirmPassword; ?>
                                </div>
                            </li>
                        </ul>
                       <div class="clear"></div>
                        <fieldset>
                            <button type="submit" id="reg_submit"></button>
                        </fieldset>
                        <div class="clear"></div>
                        </div><!-- closes form bg -->
                    </div>     
                </form>
                