<?php if(isset($this->to_show)): ?>
<article class="module width_full">
<table class="tablesorter" cellspacing="0">
	<header>
		<h3 class="tabs_involved">Content Manager</h3>
	</header>
	<?php
		$count = 0; 
		foreach($this->to_show as $row):
			if($count==0):?>
			<thead>
				<tr>
				<th><input type="checkbox" id="checkbox_head" /></th>
				<?php foreach(array_keys($this->to_show->current()->getArrayCopy()) as $tr ): ?>
					<?php if(in_array($tr,$this->fields)):?>
						<th class="header"> <?php echo ucfirst(str_replace("_", " ", $tr));?></th>
					<?php endif;?>		
				<?php endforeach;?>
				<th>Actions</th>
				</tr>
			</thead>
			<tbody>		
			<?php endif;?>
		<tr>
		<td><input type="checkbox" class="check_box_tbl" /></td>
		<?php foreach($row->getArrayCopy() as $key_field=>$field):?>
			<?php if(in_array($key_field,$this->fields)):?> 
				<td><?php echo $field;?></td>
			<?php endif;?>
		<?php endforeach;?>
			<td>
			<a href="<?php echo $this->edit_address."/".$row->id;?>"><input type="image" title="Edit" src="/img/admin/icn_edit.png" ></a>
			<a href="<?php echo $this->delete_address."/".$row->id;?>" class="delete_btn"><input type="image" title="Trash" src="/img/admin/icn_trash.png"></a>	
			</td>
		</tr>		
	<?php 
	$count ++;	
	endforeach;?>
	</tbody>
</table>
</article>
<?php else:?>
<arŧicle>
	<h4>No data present in the table</h4>
</arŧicle>
<?php endif;?>